### ISSUE TITLE
The authenticity of host 'x.x.x.x' can't be established

### ISSUE THREAD

**Issue by Honghe** [rywillia/ansible-ssh-copy-id#1]
```
➜  ansible-ssh-copy-id git:(master) ✗ ansible-playbook main.yml

PLAY [cdh] ************************************************************************************

TASK [Gathering Facts] ************************************************************************
The authenticity of host '172.24.10.150 (172.24.10.150)' can't be established.
ECDSA key fingerprint is SHA256:AMDsXXwA/NMRe2sPP2eI7jhHmw2ZG785FdR0nkkKJxw.
Are you sure you want to continue connecting (yes/no)? The authenticity of host '172.24.10.163 (172.24.10.163)' can't be established.
ECDSA key fingerprint is SHA256:AMDsXXwA/NMRe2sPP2eI7jhHmw2ZG785FdR0nkkKJxw.
Are you sure you want to continue connecting (yes/no)? fatal: [172.24.10.74]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n", "unreachable": true}
^CProcess WorkerProcess-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process WorkerProcess-1:
 [ERROR]: User interrupted execution

```

**Comment by ryankwilliams** [comment]
Hello,

The error you have pasted above looks to be prior to calling this role. Based on your error, it seems that Ansible was unsuccessful when attempting to SSH into the host you defined in your play to run against. I would suggest making sure Ansible can successfully connect to the host your play defines. Once ansible can connect successfully to the plays host, then you should be able to execute this role.

You can also configure your ansible.cfg to avoid host key checking using the _host_key_checking = False_. This would remove the need for manual input of giving yes/no to the prompt.

**Comment by ryankwilliams** [comment]
Closing this issue due to potential solution provided in previous comment and it does not seem to be related to this role.
