### ISSUE TITLE
[Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by moisawade** [rywillia/ansible-ssh-copy-id#2]
Hello,
I've got this error when trying to execute role.
Any ideas?

Details:
fatal: [10.100.54.163]: FAILED! => {
    "changed": false,
    "module_stderr": "Connection to 10.100.54.163 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_KlMico/ansible_module_ssh_copy_id.py\", line 159, in <module>\r\n    main()\r\n  File \"/tmp/ansible_KlMico/ansible_module_ssh_copy_id.py\", line 155, in main\r\n    run_module()\r\n  File \"/tmp/ansible_KlMico/ansible_module_ssh_copy_id.py\", line 108, in run_module\r\n    password=module.params['password']\r\n  File \"/usr/lib/python2.6/site-packages/paramiko/client.py\", line 277, in connect\r\n    socket.getaddrinfo(hostname, port):\r\nsocket.gaierror: [Errno -3] Temporary failure in name resolution\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by ryankwilliams** [comment]
Hello,

Based on the error you have pasted _[Errno -3] Temporary failure in name resolution_ it looks like there may have been a DNS problem. From the error message above it is hard for me to tell if the value supplied to the role for hostname was an actual FQDN or an IP address. Based on the error message it makes me think it was a FQDN and paramiko was unable to resolve the DNS lookup to the IP address.

**Comment by moisawade** [comment]
Hello, I use IP address and it's okay now for this point.
 Thanks for feedback.
