### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by moisawade** [rywillia/ansible-ssh-copy-id#3]
Hello,
I've got this following error when trying to run the playbook.

fatal: [ X.X.X.X]: FAILED! => {
    "changed": false,
    "module_stderr": "Connection to X.X.X.X closed.\r\n",
    "module_stdout": "\r\n/usr/lib/python2.6/site-packages/paramiko/client.py:93: UserWarning: Unknown ssh-rsa host key for 10.100.54.160: a7e245b944164f3b71387ed7fea2c8f4\r\n  (key.get_name(), hostname, hexlify(key.get_fingerprint())))\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_XkPLM8/ansible_module_ssh_copy_id.py\", line 161, in <module>\r\n    main()\r\n  File \"/tmp/ansible_XkPLM8/ansible_module_ssh_copy_id.py\", line 157, in main\r\n    run_module()\r\n  File \"/tmp/ansible_XkPLM8/ansible_module_ssh_copy_id.py\", line 117, in run_module\r\n    with open(module.params['ssh_public_key'], 'r') as fh:\r\nIOError: [Errno 2] No such file or directory: '/home/mwade028166/.ssh/id_rsa.pub'\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

After check, the files is at the right place.

[mwade028166@rusvindustryit03 automation]$ ls -ltr /home/mwade028166/.ssh/id_rsa.pub
-rwxrwxrwx 1 mwade028166 mwade028166 410 Jul 26 17:50 /home/mwade028166/.ssh/id_rsa.pub
[mwade028166@rusvindustryit03 automation]$

**Comment by ryankwilliams** [comment]
Hello,

Thank you for providing the error when attempting to run your playbook using this role. Could you help clarify me with regards to your playbook?

The hostname _rusvindustryit03_ is where you are issuing the ansible-playbook command? Inside your playbook the host defined is the IP _10.100.51.160_. Does that reference too _rusvindustryit03_? If so (meaning your running on your localhost where the public key is located), the role should be able to locate it.

In the case you are calling the playbook from _rusvindustryit03_ and ansible runs the playbook against _10.100.51.160_ which is a different machine. You would need to have some task to get the public key from your base machine where the playbook is called to the actual machine the playbook is executed against.

This role will be looking for the ssh public key on the host that the playbook is run against. In this case it would be looking for the key at _10.100.51.160_.

I would also like to let you know I made some enhancements to the module handling the ssh-copy-id actions to better handle errors.

**Comment by moisawade** [comment]
Hi,
I've taken the new version but still have the same error.
Am connected via ssh on 10.137.18.49 and try to share my public key on 10.100.51.160, 10.100.54.61 but for both of them i get the same error.
Here is my playbook and outcome errors.
###Playbook
---
- hosts: genesys
  gather_facts: false
  remote_user: pmsylla028359
  become: true
  roles:
    - role: ansible-ssh-copy-id-master
      hostname: "{{inventory_hostname}}"
      username: mwade028166
      password: Orange!221
      ssh_public_key: /home/mwade028166/.ssh/authorized_keys ## located on 10.137.18.49
####


###Output 
[mwade028166@rusvindustryit03 automation]$ ansible-playbook ssh-copy-id.yaml -e "user_pass=sonatel221" --ask-pass -vvv
ansible-playbook 2.5.5
  config file = /home/mwade028166/workspace/automation/ansible.cfg
  configured module search path = [u'/home/mwade028166/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /home/mwade028166/workspace/automation/ansible.cfg as config file
SSH password:
Parsed /home/mwade028166/workspace/automation/my_hosts/genesys.yaml inventory source with ini plugin
Parsed /home/mwade028166/workspace/automation/my_hosts/vision.yaml inventory source with ini plugin
PLAYBOOK: ssh-copy-id.yaml ******************************************************************************************************************************************************************************************************************
1 plays in ssh-copy-id.yaml
PLAY [genesys] ******************************************************************************************************************************************************************************************************************************
META: ran handlers
TASK [ansible-ssh-copy-id-master : Inject SSH public key into remote system] ****************************************************************************************************************************************************************
task path: /home/mwade028166/workspace/automation/roles/ansible-ssh-copy-id-master/tasks/main.yml:4
Using module file /home/mwade028166/workspace/automation/roles/ansible-ssh-copy-id-master/library/ssh_copy_id.py
<10.100.54.160> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
Using module file /home/mwade028166/workspace/automation/roles/ansible-ssh-copy-id-master/library/ssh_copy_id.py
<10.100.54.61> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.160> SSH: EXEC sshpass -d15 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.160 '/bin/sh -c '"'"'echo ~pmsylla028359 && sleep 0'"'"''
<10.100.54.61> SSH: EXEC sshpass -d16 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.61 '/bin/sh -c '"'"'echo ~pmsylla028359 && sleep 0'"'"''
<10.100.54.61> (0, '/home/pmsylla028359\n', '')
<10.100.54.61> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.61> SSH: EXEC sshpass -d16 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.61 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943 `" && echo ansible-tmp-1533288186.29-104651881779943="` echo /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943 `" ) && sleep 0'"'"''
<10.100.54.160> (0, '/home/pmsylla028359\n', '')
<10.100.54.160> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.160> SSH: EXEC sshpass -d15 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.160 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881 `" && echo ansible-tmp-1533288186.29-126035633228881="` echo /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881 `" ) && sleep 0'"'"''
<10.100.54.61> (0, 'ansible-tmp-1533288186.29-104651881779943=/home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943\n', '')
<10.100.54.61> PUT /home/mwade028166/.ansible/tmp/ansible-local-18581UUtQ_s/tmpRqkBtC TO /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ssh_copy_id.py
<10.100.54.61> SSH: EXEC sshpass -d16 sftp -o BatchMode=no -b - -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 '[10.100.54.61]'
<10.100.54.160> (0, 'ansible-tmp-1533288186.29-126035633228881=/home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881\n', '')
<10.100.54.160> PUT /home/mwade028166/.ansible/tmp/ansible-local-18581UUtQ_s/tmpLkN4so TO /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ssh_copy_id.py
<10.100.54.160> SSH: EXEC sshpass -d15 sftp -o BatchMode=no -b - -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 '[10.100.54.160]'
<10.100.54.61> (0, 'sftp> put /home/mwade028166/.ansible/tmp/ansible-local-18581UUtQ_s/tmpRqkBtC /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ssh_copy_id.py\n', '')
<10.100.54.61> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.61> SSH: EXEC sshpass -d16 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.61 '/bin/sh -c '"'"'chmod u+x /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ssh_copy_id.py && sleep 0'"'"''
<10.100.54.160> (0, 'sftp> put /home/mwade028166/.ansible/tmp/ansible-local-18581UUtQ_s/tmpLkN4so /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ssh_copy_id.py\n', '')
<10.100.54.160> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.160> SSH: EXEC sshpass -d15 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.160 '/bin/sh -c '"'"'chmod u+x /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ssh_copy_id.py && sleep 0'"'"''
<10.100.54.61> (0, '', '')
<10.100.54.61> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.61> SSH: EXEC sshpass -d16 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 -tt 10.100.54.61 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=hoxjttisgqjmoylrqfncyafvoorjgkjr] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-hoxjttisgqjmoylrqfncyafvoorjgkjr; /usr/bin/python /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ssh_copy_id.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<10.100.54.160> (0, '', '')
<10.100.54.160> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.160> SSH: EXEC sshpass -d15 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 -tt 10.100.54.160 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=fworvxobpcwqtimflafeuvcuhwckspxl] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-fworvxobpcwqtimflafeuvcuhwckspxl; /usr/bin/python /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ssh_copy_id.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Escalation succeeded
Escalation succeeded
<10.100.54.61> (1, '\r\n\r\n{"msg": "Unable to locate ssh public key /home/mwade028166/.ssh/authorized_keys", "failed": true, "invocation": {"module_args": {"username": "mwade028166", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "hostname": "10.100.54.61", "ssh_public_key": "/home/mwade028166/.ssh/authorized_keys"}}}\r\n', 'Connection to 10.100.54.61 closed.\r\n')
<10.100.54.61> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.61> SSH: EXEC sshpass -d16 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.61 '/bin/sh -c '"'"'rm -f -r /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-104651881779943/ > /dev/null 2>&1 && sleep 0'"'"''
<10.100.54.160> (1, '\r\n\r\n{"msg": "Unable to locate ssh public key /home/mwade028166/.ssh/authorized_keys", "failed": true, "invocation": {"module_args": {"username": "mwade028166", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "hostname": "10.100.54.160", "ssh_public_key": "/home/mwade028166/.ssh/authorized_keys"}}}\r\n', 'Connection to 10.100.54.160 closed.\r\n')
<10.100.54.160> ESTABLISH SSH CONNECTION FOR USER: pmsylla028359
<10.100.54.160> SSH: EXEC sshpass -d15 ssh -o ControlMaster=no -o User=pmsylla028359 -o ConnectTimeout=10 10.100.54.160 '/bin/sh -c '"'"'rm -f -r /home/pmsylla028359/.ansible/tmp/ansible-tmp-1533288186.29-126035633228881/ > /dev/null 2>&1 && sleep 0'"'"''
<10.100.54.61> (0, '', '')
fatal: [10.100.54.61]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "10.100.54.61",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssh_public_key": "/home/mwade028166/.ssh/authorized_keys",
            "username": "mwade028166"
        }
    },
    "msg": "Unable to locate ssh public key /home/mwade028166/.ssh/authorized_keys"
}
<10.100.54.160> (0, '', '')
fatal: [10.100.54.160]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "10.100.54.160",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssh_public_key": "/home/mwade028166/.ssh/authorized_keys",
            "username": "mwade028166"
        }
    },
    "msg": "Unable to locate ssh public key /home/mwade028166/.ssh/authorized_keys"
}
PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.100.54.160              : ok=0    changed=0    unreachable=0    failed=1
10.100.54.61               : ok=0    changed=0    unreachable=0    failed=1

####

**Comment by ryankwilliams** [comment]
Thank you for providing details about your playbook and the output with verbosity enabled!

After looking at the playbook output you provided. It looks like the role is being run on the incorrect host where your public key is located. From your playbook output based on the logs, it looks like the playbook was trying to run the role against 10.100.54.160 and 10.100.54.61. Which are the machines you wish to deploy your public key too.

Please correct me if I am wrong but what you are trying to do is push your public key on 10.137.18.49 to those remote machines (10.100.54.160 & 10.100.54.61) for passwordless authentication. You should modify your playbook to look like below:

```yaml
---
- name: deploy public ssh key to remote machines
  hosts: <group name for 10.137.18.49>

  roles:
    - role: rywillia.ssh-copy-id
      vars:
        hostname: 10.100.54.160
        username: username
        password: password
        ssh_public_key: /home/mwade028166/.ssh/authorized_keys ## located on 10.137.18.49

    - role: rywillia.ssh-copy-id
      vars:
        hostname: 10.100.54.61
        username: username
        password: password
        ssh_public_key: /home/mwade028166/.ssh/authorized_keys ## located on 10.137.18.49
```

When executing this playbook by ansible, ansible will run the role against 10.137.18.49. When this role starts to run, it will be able to locate the ssh public key since the role is running on 10.137.18.49 which is where the key is located.

A quick summary about this role. You supply it the FQDN or IP address of a remote machine you want to deploy a public key to, the username/password to connect to the defined remote machine and the absolute path to the ssh public key to deploy. The role then uses the paramiko library to create a ssh connection to the machine that was described by the vars to the role. Once connection is established, it will go ahead and deploy your public key you supplied into the remote machine.

**Comment by moisawade** [comment]
Hello dear, 
After adapting my playbook by following your advices, find bellow the issues.
#####PlayBook running on 10.137.18.49 ###
---
- name: deploy public ssh key to remote machines
  hosts: topmanager
  gather_facts: true
  remote_user: mwade028166
  become: false
  roles:
    - role: ansible-ssh-copy-id-master
      vars:
      hostname: 10.100.54.160
      username: pmsylla028359
      password: ##########
      ssh_public_key: /home/mwade028166/.ssh/id_rsa.pub ## located on 10.137.18.49
    - role: ansible-ssh-copy-id-master
      vars:
      hostname: 10.100.54.61
      username: pmsylla028359
      password: ##########
      ssh_public_key: /home/mwade028166/.ssh/id_rsa.pub ## located on 10.137.18.49

#####

<10.137.18.49> (0, '', '')
fatal: [10.137.18.49]: FAILED! => {
    "changed": false,
    "module_stderr": "Connection to 10.137.18.49 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_jRm40Z/ansible_module_ssh_copy_id.py\", line 195, in <module>\r\n    main()\r\n  File \"/tmp/ansible_jRm40Z/ansible_module_ssh_copy_id.py\", line 191, in main\r\n    run_module()\r\n  File \"/tmp/ansible_jRm40Z/ansible_module_ssh_copy_id.py\", line 125, in run_module\r\n    password=password\r\n  File \"/usr/lib/python2.7/site-packages/paramiko/client.py\", line 361, in connect\r\n    server_key)\r\nTypeError: unbound method missing_host_key() must be called with WarningPolicy instance as first argument (got SSHClient instance instead)\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

**Comment by moisawade** [comment]
Hello dear,
I've passed this step by adding this line.

 # create ssh client via paramiko
    ssh_con = paramiko.SSHClient()
    **ssh_con.load_system_host_keys()**
    ssh_con.set_missing_host_key_policy(paramiko.WarningPolicy)

Now everything works fine.
Thanks a bundle, you rock 👍 👍 👍

**Comment by moisawade** [comment]
It's okay now.
